/*********************  P r o g r a m  -  M o d u l e ***********************/
/*!
 *        \file  z147_doc.c
 *
 *      \author  APatil
 *        $Date: 2015/10/16 18:08:00 $
 *        $Revision: 1.1 $
 *
 *      \brief   User documentation for MDIS5 Z147 driver
 *
 *     Required: -
 *
 *     \switches -
 */
 /*-------------------------------[ History ]--------------------------------
 *
 * $Log: z147_doc.c,v $
 *
 * Revision 1.1  2004/06/18 14:29:51  ub
 * Initial Revision
 *
 *---------------------------------------------------------------------------
 * (c) Copyright 2004 by MEN Mikro Elektronik GmbH, Nuernberg, Germany
 ****************************************************************************/

/*! \mainpage
    The 13Z147 is a transceiver driver for the MEN_ARINC_717 RX and TX channels (16Z147).
	The MEN_ARINC_717 is a memory mapped IP-Core, which is used to receive and transmit
	data over the serial lines.
	The RX and TX channel can be used independently using RX and TX instance of the driver.
	Each instance of the RX and TX can be configured independently and has its own interrupt
	handling. 
	The driver supports 8 different data rates for transmission and reception:
	-	768 Bits/sec.   ( 64  words/sec.)
	-	1536 Bits/sec. (128 words/sec.)
	-	3072 Bits/sec. (256 words/sec.)
	-	6144 Bits/sec. (512 words /sec.)
	-	12288 Bits/sec. (1024 words/sec.)
	-	24576 Bits/sec. (2048 words/sec.)
	-	49152 Bits/sec. (4096 words/sec.)
	-	98304 Bits/sec. (8192 words/sec.)	
	
    The 13Z147 provides following possibilities to configure:
    - Transmit/Receive Data rate
	- Transmit/Receive mode Harvard Bi-Phase/Bipolar Return to Zero
	- Receive synchronization mode
	
/reset

    \n
    \section Variants Variants
    (no variants)

    \n \section FuncDescTx Functional Description (Transmit)

    \n \subsection General General
	The transmit instance of the driver 13Z147 can be configured and used independently.
	The configuration of the transmit driver must be same as the receiver of the other end,
	in order to work the communication.
	The default configuration of the transmit driver is compatible to the default configuration
	of the receive driver. Any change in the transmit driver suppose to be taken into 
	consideration for the receive driver in order to avoid failure of the communication.
	
    \n \subsection write Writing
	The M_setblock writes data from the user provided buffer to the device. The configured data
	rate needs to be taken into consideration in order to know about user data size.
	As per the ARINC 717 specification, the data transmission is cyclic. The cyclic 
	transmission is triggered by first data request by the user. Once the transmitter finds
	synchronization	with receiver, it stays in sync by transmitting the same data continuously.
	When the user transmits new data, it will be first stored internally and transmitted with
	new frame cycle. 	
	
    \n \subsection interrupts Signals
    
    A signal is generated by the driver, which was assigned using SetStat Z247_SET_SIGNAL to 
	the application, when a transmission request is completed. The user	can uninstall signal
	using Z247_CLR_SIGNAL.

	\n \subsection setget Driver Configuration 
	The driver can be configured using M_setstat(), using following options:
	
    <table border="0">	   
	<tr>
	<td><b>Config Parameter</b></td>
	<td><b>Value</b></td>
	<td><b>Description</b></td></tr>

    <tr><td>Z247_TX_DATA_RATE</td><td> - 0b000</td><td>: 768 Bits/sec. (64 words/sec.)</td></tr>

    <tr><td>   </td><td> - 0b001   </td>   <td>: 1536Bits/sec.   (128 words/sec.)</td></tr>
    <tr><td>   </td><td> - 0b010   </td>    <td>: 3072 Bits/sec.   (256 words/sec.)</td></tr>
    <tr><td>   </td><td> - 0b011   </td>    <td>: 6144 Bits/sec.   (512 words/sec.)</td></tr>
    <tr><td>   </td><td> - 0b100   </td>    <td>: 12288 Bits/sec. (1024 words/sec.)</td></tr>
	<tr><td>   </td><td> - 0b101   </td>    <td>: 24576 Bits/sec. (2048 words/sec.)</td></tr>
	<tr><td>   </td><td> - 0b110   </td>    <td>: 49152 Bits/sec. (4096 words/sec.)</td></tr>
	<tr><td>   </td><td> - 0b111   </td>    <td>: 98304 Bits/sec. (8192 words/sec.)</td></tr>

    </table>
	
    \n \subsection default Default values
    M_open() and M_close() configures the transmit driver as follows: 
    
    - Transmit Rate: 768 Bits/sec. ( 64  words/sec.)
	- Transmit mode: Harvard Bi-Phase 
	
    \n \section api_functions Supported API Functions of the Transmit Driver

    <table border="0">
    <tr>
        <td><b>API function</b></td>
        <td><b>Functionality</b></td>
        <td><b>Corresponding low level function</b></td></tr>

    <tr><td>M_open()</td><td>Open device</td><td>Z247_Init()</td></tr>

    <tr><td>M_close()     </td><td>Close device             </td>
    <td>Z247_Exit())</td></tr>
    <tr><td>M_setblock()  </td><td>Block write from device  </td>
    <td>Z247_BlockWrite()</td></tr>
    <tr><td>M_setstat()   </td><td>Set device parameter     </td>
    <td>Z247_SetStat()</td></tr>
    <tr><td>M_getstat()   </td><td>Get device parameter     </td>
    <td>Z247_GetStat()</td></tr>

    </table>
	
	    \n \section FuncDescRx Functional Description (Receive)

    \n \subsection General General
	The receive instance of the driver 13Z147 can be configured and used independently.
	The configuration of the receive driver must be same as the transmitter of the other end,
	in order to work the communication.
	The default configuration of the receive driver is compatible to the default configuration
	of the transmit driver.	Any change in the receive driver suppose to be taken into 
	consideration for the transmit driver in order to avoid failure of the communication.


    \n \subsection read Reading 
	The M_getblock reads data from the driver. The driver receives the data and store it in 
	an internal buffer.	When a data is received a signal is generated by the driver, which was
	assigned using SetStat Z147_SET_SIGNAL to the application.	
	As per the ARINC 717 specification, the data reception is cyclic once the receiver is in sync.
	The receiver first get synchronized with the transmitter. Once the receiver is in synchronization	
	with transmitter, the data can be received. The user will get received data along with the
	sync words 0x247 (SUB_FRAME_1), 0x5B8 (SUB_FRAME_2),
	0xA47 (SUB_FRAME_3), 0xDB8(SUB_FRAME_4), to identify the subframes.

    \n \subsection interrupts Interrupt and Signal
    
    The driver will send the signal which was assigned using SetStat Z147_SET_SIGNAL to the 
	application when a data is received. Uninstall signal using Z147_CLR_SIGNAL.

  	\n \subsection setget Driver Configuration 
	The driver can be configured using M_setstat(), using following options:
	
	    <table border="0">	   
	<tr>
	<td><b>Config Parameter</b></td>
	<td><b> Values </b></td>
	<td><b>Description</b></td></tr>

    <tr><td>Z147_RX_DATA_RATE</td><td> - 0b000</td><td>: 768 Bits/sec. (64 words/sec.)</td></tr>

    <tr><td>   </td><td> - 0b001 </td>   <td>: 1536Bits/sec.   (128 words/sec.)</td></tr>
    <tr><td>   </td><td> - 0b010 </td>    <td>: 3072 Bits/sec.   (256 words/sec.)</td></tr>
    <tr><td>   </td><td> - 0b011   </td>    <td>: 6144 Bits/sec.   (512 words/sec.)</td></tr>
    <tr><td>   </td><td> - 0b100   </td>    <td>: 12288 Bits/sec. (1024 words/sec.)</td></tr>
	<tr><td>   </td><td> - 0b101   </td>    <td>: 24576 Bits/sec. (2048 words/sec.)</td></tr>
	<tr><td>   </td><td> - 0b110   </td>    <td>: 49152 Bits/sec. (4096 words/sec.)</td></tr>
	<tr><td>   </td><td> - 0b111   </td>    <td>: 98304 Bits/sec. (8192 words/sec.)</td></tr>
	<tr><td>Z147_RX_SYNC_CFG</td><td> -  0b000</td><td>: No synchronization: Start receiving from the first detected edge </td></tr>
    <tr><td>   </td><td> -  0b001   </td>   <td>: Part synchronization: Start receiving when only two sync words are in the correct order</td></tr>
    <tr><td>   </td><td> -  0b010   </td>    <td>: Full synchronization: Start receiving when all sync words came in the correct order</td></tr>
    <tr><td>   </td><td> -  0b011   </td>    <td>: Reserved (Full synchronization shall be used)</td></tr>

    </table>
	
   
    \n \subsection default Default values
    M_open() and M_close() configures the Receive driver as follows: 
    
    - Receive Rate: 768 Bits/sec. ( 64  words/sec.)
	- Receive mode: Harvard Bi-Phase 
	- Receive sync mode: 0b10 = Full synchronization 


    \n \section api_functions Supported API Functions of the Receive Driver
	
	<table border="0">
    <tr>
        <td><b>API function</b></td>
        <td><b>Functionality</b></td>
        <td><b>Corresponding low level function</b></td></tr>

    <tr><td>M_open()</td><td>Open device</td><td>Z147_Init()</td></tr>

    <tr><td>M_close()     </td><td>Close device             </td>
    <td>Z147_Exit())</td></tr>
	<tr><td>M_getblock()  </td><td>Block read from device   </td>
    <td>Z147_BlockRead()</td></tr>
    
    <tr><td>M_setstat()   </td><td>Set device parameter     </td>
    <td>Z147_SetStat()</td></tr>
    <tr><td>M_getstat()   </td><td>Get device parameter     </td>
    <td>Z147_GetStat()</td></tr>

    </table>

    \n \section descriptor_entries Descriptor Entries
    (no descriptor entries supported)    
    
    \n \section codes Z147 specific Getstat/Setstat codes
    see \ref getstat_setstat_codes "section about Getstat/Setstat codes"

    \n \section Documents Overview of all Documents

    \subsection z147_example  Simple example for using the driver
    z147_example.c (see example section)

*/

/** \example z147_example.c
Simple example for driver usage
*/

/** \example z147_example.c */

/*! \page dummy
  \menimages
*/

